server:
  port: 9004

spring:
  application:
    name: AUTH-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    url: jdbc:postgresql://localhost:5432/vifrin
    username: postgres
    password: '09071999'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: mymoments.vn@gmail.com
    password: 12345a@A
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
token:
  expiration:
    time: 7
