server:
  port: 9012

spring:
  application:
    name: NOTIFICATION-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

  datasource:
    url: jdbc:postgresql://localhost:5432/vifrin
    username: postgres
    password: '09071999'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
        bindings:
          PostChanged:
            consumer:
              startOffset: latest
              autoCommitOffset: false
          CommentChanged:
            consumer:
              startOffset: latest
              autoCommitOffset: false
      bindings:
        CommentChanged:
          destination: vifrin-comment-changed
          contentType: application/json
          group: graphService
          consumer:
            startOffset: latest
            autoCommitOffset: false
        PostChanged:
          destination: vifrin-post-changed
          contentType: application/json
          group: graphService
          consumer:
            startOffset: latest
            autoCommitOffset: false
        UserChanged:
          destination: vifrin-user-changed
          contentType: application/json