server:
  port: 9006

spring:
  application:
    name: COMMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

  datasource:
    url: jdbc:postgresql://localhost:5432/vifrin
    username: postgres
    password: '09071999'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        CommentChanged:
          destination: vifrin-comment-changed
          contentType: application/json