version: '3.1'
services:
  postgresql:
    image: postgres
    container_name: pg-docker
    hostname: pg-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=vifrin
    restart: always
    networks:
      - be-common-network

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
      # PGADMIN_LISTEN_PORT = 80
    ports:
      - "5050:80"
    networks:
      - be-common-network


  service-registry:
    build:
      context: ./service-registry
      args:
        JAR_FILE: service-registry-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: service-registry
    container_name: service-registry
    hostname: service-registry
    ports:
      - "8761:8761"
    networks:
      - be-common-network
    environment:
      - SERVER_PORT=8761
      - SPRING_PROFILES_ACTIVE=docker

  user-service:
    build:
      context: ./user-service
      args:
        JAR_FILE: user-service-0.0.1-SNAPSHOT.jar
      dockerfile: Dockerfile
    image: user-service
    container_name: user-service
    hostname: user-service
    ports:
      - "9002:9002"
    networks:
      - be-common-network
    depends_on:
      - service-registry
    environment:
      - SERVER_PORT=9002
      - SPRING_PROFILES_ACTIVE=docker
networks:
  be-common-network:
    driver: bridge