version: '3.1'
services:
#  kafka:
#    image: wurstmeister/kafka
#    container_name: "kafka"
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
#      - KAFKA_ADVERTISED_PORT=9092
#      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
#    depends_on:
#      - zookeeper
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
#  cassandra:
#    image: cassandra:latest
#    ports:
#      - "7000:7000"
#      - "9042:9042"
#    volumes:
#      - /home/amr/instaCassandra:/var/lib/cassandra

#  db:
#    container_name: vifrin-db
#    restart: unless-stopped
#    image: mysql:5.7
#    command: --innodb_use_native_aio=0
#    environment:
#      MYSQL_ROOT_PASSWORD: 'password'
#      MYSQL_DATABASE: 'vifrin'
#    ports:
#      - "3306:3306"
#    expose:
#      - "3306"
#    volumes:
#      - ./db:/var/lib/mysql

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  networks:
    postgres:
      driver: bridge

  volumes:
    postgres:
    pgadmin: