server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shabbirdwd53/config-server
          clone-on-start: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vifrin
    username: anhtrt
    password: 09071999
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
