server:
  port: 9005

spring:
  application:
    name: POST-SERVICE

  zipkin:
    base-url: http://127.0.0.1:9411/

  data:
    cassandra:
      keyspaceName: insta_feed
      contactPoints: localhost
      port: 9042
      schema-action: CREATE_IF_NOT_EXISTS

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
        bindings:
          momentsPostChanged:
            consumer:
              startOffset: latest
              autoCommitOffset: false
      bindings:
        momentsPostChanged:
          destination: moments.post.changed
          contentType: application/json
          group: graphService
          consumer:
            startOffset: latest
            autoCommitOffset: false