server:
  port: 9016

spring:
  application:
    name: HOTEL-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

  datasource:
    url: jdbc:postgresql://localhost:5432/vifrin
    username: postgres
    password: '09071999'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          CommentChanged:
            consumer:
              startOffset: latest
              autoCommitOffset: false
      bindings:
        CommentChanged:
          destination: vifrin-comment-changed
          contentType: application/json
          group: graphService
          consumer:
            startOffset: latest
            autoCommitOffset: false
