server:
  port: 9017

spring:
  application:
    name: CHAT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

  datasource:
    url: jdbc:postgresql://localhost:5432/vifrin
    username: postgres
    password: '09071999'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  session:
    store-type: redis
  redis:
    port: 6379
redis:
  embedded:
    port: 6379
chat:
  max-profanity-level: 5
  disallowed-words: damn, crap, ass
  destinations:
    login: /topic/chat.login
    logout: /topic/chat.logout